<?php
/**
 * Plugin Name: RevLocal
 * Plugin URI: http://revlocal.com/
 * Description: For RevLocal admins only.
 * Version: 1.0.0
 * Author: Nathanael Gray
 * Author URI: http://thangray.ninja/
 * License: GPL2
 */

	// RevLocal Options
	if( function_exists('acf_add_options_page') ) {
	
		$page = acf_add_options_page(array(
			'page_title' 	=> 'RevLocal',
			'menu_title' 	=> 'RevLocal',
			'icon_url'		=> get_template_directory_uri() . '/../Divi-Child/img/revlocal-logo.png',
			'menu_slug' 	=> 'revlocal-settings',
			'capability' 	=> 'edit_posts',
			'position'		=> '',
			'redirect' 		=> false
		));
	 
	}

	if( function_exists('register_field_group') ):

	register_field_group(array (
		'key' => 'group_548b164501e66',
		'title' => 'Settings',
		'fields' => array (
			array (
				'key' => 'field_548b472226e60',
				'label' => 'General',
				'name' => '',
				'prefix' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'key' => 'field_548b4a1126e61',
				'label' => 'Logo',
				'name' => 'logo',
				'prefix' => '',
				'type' => 'image',
				'instructions' => 'If you don\'t have a logo, your website name will display instead.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => 32,
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_548b166442047',
				'label' => 'Contact Information',
				'name' => '',
				'prefix' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'key' => 'field_548b169d42048',
				'label' => 'Header Contact Numbers',
				'name' => 'primary_numbers',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => 'These contact numbers will display in the header of your website as a link.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'layout' => 'block',
				'button_label' => 'Add a Primary Contact Number',
				'sub_fields' => array (
					array (
						'key' => 'field_548b172c4204a',
						'label' => 'Primary Number',
						'name' => 'primary_number',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '(555) 555-5555',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),
			array (
				'key' => 'field_548b40ae6b3fb',
				'label' => 'Header Addresses',
				'name' => 'primary_address',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => 'These addresses will display in the header of your website as a link.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'layout' => 'block',
				'button_label' => 'Add an Address',
				'sub_fields' => array (
					array (
						'key' => 'field_548b40d86b3fc',
						'label' => 'Street Address',
						'name' => 'street',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_548b40fe6b3fd',
						'label' => 'City',
						'name' => 'city',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_548b410a6b3fe',
						'label' => 'State',
						'name' => 'state',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_548b41276b400',
						'label' => 'Zip',
						'name' => 'zip',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_548b412f6b401',
						'label' => 'Google Maps Link',
						'name' => 'google_maps_link',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '<a href="http://maps.google.com" target="_blank">Search for your address and paste the full url here.</a>',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),
			array (
				'key' => 'field_548b577667659',
				'label' => 'Header',
				'name' => '',
				'prefix' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'key' => 'field_548b577f6765a',
				'label' => 'Head Scripts',
				'name' => 'head_scripts',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'layout' => 'block',
				'button_label' => 'Add a Script',
				'sub_fields' => array (
					array (
						'key' => 'field_548b577f6765b',
						'label' => 'Script',
						'name' => 'script',
						'prefix' => '',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 50,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '<!-- Google Analytics: change UA-XXXXX-X to be your site\'s ID. --><script> 		(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]= 		function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date; e=o.createElement(i);r=o.getElementsByTagName(i)[0]; 		e.src=\'//www.google-analytics.com/analytics.js\'; 		r.parentNode.insertBefore(e,r)}(window,document,\'script\',\'ga\')); 		ga(\'create\',\'UA-XXXXX-X\');ga(\'send\',\'pageview\'); </script>',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),
			array (
				'key' => 'field_548b550cb3481',
				'label' => 'Footer',
				'name' => '',
				'prefix' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'key' => 'field_548b5533b3482',
				'label' => 'Footer Scripts',
				'name' => 'footer_scripts',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'layout' => 'block',
				'button_label' => 'Add a Script',
				'sub_fields' => array (
					array (
						'key' => 'field_548b5569b3483',
						'label' => 'Script',
						'name' => 'script',
						'prefix' => '',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 50,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '<!-- Google Analytics: change UA-XXXXX-X to be your site\'s ID. --><script> 		(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]= 		function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date; e=o.createElement(i);r=o.getElementsByTagName(i)[0]; 		e.src=\'//www.google-analytics.com/analytics.js\'; 		r.parentNode.insertBefore(e,r)}(window,document,\'script\',\'ga\')); 		ga(\'create\',\'UA-XXXXX-X\');ga(\'send\',\'pageview\'); </script>',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'revlocal-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	endif;
?>